### ISSUE TITLE
Multiple elastic search terms: COSMOS search API

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/Cosmos#108]
This could be a front or backend issue. The question is how are multiple search terms handled when ElasticSearch is used:

https://cosmos.wisc.edu/sets/covid/?backend=ElasticSearch&query=IC50%20Ribavirin&type=Table

Example of the returned objects:
http://cosmos3.chtc.wisc.edu:8081/search?id=1007497
http://cosmos3.chtc.wisc.edu:8081/search?id=1584646
The term Ribavirin does not appear anywhere here.

**Comment by iross** [comment]
https://github.com/UW-COSMOS/Cosmos/blob/master/cosmos/birdnest_backend/birdnest_backend/app.py#L268

Looks like it does a "match" as opposed to a "match phrase" (which is what we use in the xDD API). So multiple words are treated as an OR.

**Comment by cambro** [comment]
That's what I thought. We should probably try to incorporate a switch for how multiple terms are handled in ES, which requires both front end and back end work. The first step is to distinguish multiple terms from a search phrase. Comma-separation would probably be best. Want to coordinate with @davenquinn about this @iross?

**Comment by davenquinn** [comment]
If we default to "and" (match phrase I guess) and split the search string on commas to generate "or" relationships, could this be done without involving the frontend?

**Comment by iross** [comment]
"match phrase" isn't just an "and", it's a "search for this string as a
complete phrase"

So really there's three modes possible:

"novel coronavirus" (the phrase)
"novel" and "coronavirus" (both in the document, but not necessarily
adjacent)
"novel" or "coronavirus"

I think a default of phrase matching, with phrases separated by comma makes
sense. But I'm less sure about whether a comma-separated list should be
ORed or ANDed by default.

**Comment by cambro** [comment]
Exactly as stated.
1) multiple terms no commas is a phrase
2) multiple terms, comma separated: default to inclusive "and"

**Comment by davenquinn** [comment]
OK, so we would need an and/or switch in the API and frontend.

**Comment by iross** [comment]
Logic has been updated in the live instance. on the `search_es_objects` endpoint:

- Search now uses `match_phrase` by default, so multiple terms with no commas is searched as a full phrase
- Comma-separated lists are treated as separate terms, defaulting to and
- `&search_logic=any` will switch comma-separated term lists to use OR logic.

Keeping this open until I propagate the changes back into master.

**Comment by cambro** [comment]
See this issue for possible lingering problem:
https://github.com/UW-COSMOS/cosmos-visualizer/issues/48

**Comment by davenquinn** [comment]
Added `search_logic` to frontend in COSMOS/cosmos-visualizer#4e81d1d.

**Comment by ankur-gos** [comment]
@iross are the changes in master for AND/OR logic?

**Comment by iross** [comment]
Merged in ages ago. Closing.
