### ISSUE TITLE
Ingest pipeline fails with RecursionError

### ISSUE THREAD

**Issue by ilmcconnell** [UW-COSMOS/Cosmos#116]
**Code**: branch apiv1 
**Re-create**: run on cosmos0003, with two gpus in dask cluster (spawn_dask_cluster_2_gpu.sh), run ingestion script (ingest_documents_timing.sh)
**Result**: Ingestion fails with error on this document: 
[571f511a642f88805083527c.pdf](https://github.com/UW-COSMOS/Cosmos/files/5072667/571f511a642f88805083527c.pdf)

**Error**:

> RecursionError: maximum recursion depth exceeded
> distributed.worker - WARNING -  Compute Failed
> Function:  pdf_to_images
> args:      ('/hdd/iain/covid_docs_25Mar_all/571f511a642f88805083527c.pdf')
> kwargs:    {}
> Exception: Exception('Parsing error', 'maximum recursion depth exceeded')
>

**Comment by ankur-gos** [comment]
Fixed with #120
