### ISSUE TITLE
Ingest Pipeline fails - 'PSKeyword' object is not iterable

### ISSUE THREAD

**Issue by ilmcconnell** [UW-COSMOS/Cosmos#117]
**Code**: branch apiv1 
**Re-create**: run on cosmos0003, with two gpus in dask cluster (spawn_dask_cluster_2_gpu.sh), run ingestion script (ingest_documents_timing.sh)
**Result**: Ingestion fails with error on these documents: [5e7a4b17998e17af82661ba6.pdf](https://github.com/UW-COSMOS/Cosmos/files/5072671/5e7a4b17998e17af82661ba6.pdf)
[593b59cdcf58f13177abb084.pdf](https://github.com/UW-COSMOS/Cosmos/files/5072696/593b59cdcf58f13177abb084.pdf)
[5e79e8ce998e17af82660f6f.pdf](https://github.com/UW-COSMOS/Cosmos/files/5072700/5e79e8ce998e17af82660f6f.pdf)

**Error**:

> ERROR :: 2020-08-12 13:05:58,334 :: 'PSKeyword' object is not iterable
> Traceback (most recent call last):
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/ingest.py", line 198, in pdf_to_images
>     meta, limit = parse_pdf(filename)
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/utils/pdf_extractor.py", line 45, in parse_pdf
>     interpreter.process_page(page)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 895, in process_page
>     self.render_contents(page.resources, page.contents, ctm=ctm)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 908, in render_contents
>     self.execute(list_value(streams))
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 933, in execute
>     func(*args)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/pdfminer/pdfinterp.py", line 803, in do_TJ
>     self.graphicstate.copy())
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/pdfminer/pdfdevice.py", line 83, in render_string
>     graphicstate)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/pdfminer/pdfdevice.py", line 96, in render_string_horizontal
>     for cid in font.decode(obj):
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/pdfminer/pdffont.py", line 523, in decode
>     return bytearray(bytes)  # map(ord, bytes)
> TypeError: 'PSKeyword' object is not iterable
> distributed.worker - WARNING -  Compute Failed
> Function:  pdf_to_images
> args:      ('/hdd/iain/covid_docs_25Mar_all/5e7a4b17998e17af82661ba6.pdf')
> kwargs:    {}
> Exception: Exception('Parsing error', "'PSKeyword' object is not iterable")
>

**Comment by ankur-gos** [comment]
Fixed with #120
