### ISSUE TITLE
Ingest Pipeline fails with ''

### ISSUE THREAD

**Issue by ilmcconnell** [UW-COSMOS/Cosmos#118]
**Code**: branch apiv1 
**Re-create**: run on cosmos0003, with two gpus in dask cluster (spawn_dask_cluster_2_gpu.sh), run ingestion script (ingest_documents_timing.sh)
**Result**: Ingestion fails with error on this document: [5e78f996998e17af8265ef95.pdf](https://github.com/UW-COSMOS/Cosmos/files/5072707/5e78f996998e17af8265ef95.pdf)

**Error**:

> ERROR :: 2020-08-13 11:17:04,329 :: 
> Traceback (most recent call last):
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/ingest.py", line 198, in pdf_to_images
>     meta, limit = parse_pdf(filename)
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/utils/pdf_extractor.py", line 57, in parse_pdf
>     texts.append(line.get_text().strip())
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/utils/pdf_extractor.py", line 57, in parse_pdf
>     texts.append(line.get_text().strip())
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/bdb.py", line 88, in trace_dispatch
>     return self.dispatch_line(frame)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/bdb.py", line 113, in dispatch_line
>     if self.quitting: raise BdbQuit
> bdb.BdbQuit
> distributed.worker - WARNING -  Compute Failed
> Function:  pdf_to_images
> args:      ('/hdd/iain/covid_docs_25Mar_all/5e78f996998e17af8265ef95.pdf')
> kwargs:    {}
> Exception: Exception('Parsing error', '')

**Comment by ankur-gos** [comment]
Fixed with #120
