### ISSUE TITLE
Ingest pipeline fails with ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by ilmcconnell** [UW-COSMOS/Cosmos#119]
**Code**: branch apiv1 
**Re-create**: run on cosmos0003, with one gpu in dask cluster (spawn_dask_cluster.sh), run ingestion script (ingest_documents_timing.sh)
**Result**: Ingestion fails with error on these documents: 
[5a15d754cf58f10f6558336a.pdf](https://github.com/UW-COSMOS/Cosmos/files/5075193/5a15d754cf58f10f6558336a.pdf)
[5e7b01ae998e17af82663153.pdf](https://github.com/UW-COSMOS/Cosmos/files/5076861/5e7b01ae998e17af82663153.pdf)
[5e7a522d998e17af82661c81.pdf](https://github.com/UW-COSMOS/Cosmos/files/5079836/5e7a522d998e17af82661c81.pdf)
[5e7a522d998e17af82661c82.pdf](https://github.com/UW-COSMOS/Cosmos/files/5078035/5e7a522d998e17af82661c82.pdf)
[5e7ac2a2998e17af82662b2f.pdf](https://github.com/UW-COSMOS/Cosmos/files/5079115/5e7ac2a2998e17af82662b2f.pdf)
[5cd955ca0b45c76caf8922bc.pdf](https://github.com/UW-COSMOS/Cosmos/files/5079116/5cd955ca0b45c76caf8922bc.pdf)
[5e7900aa998e17af8265f0c8.pdf](https://github.com/UW-COSMOS/Cosmos/files/5079117/5e7900aa998e17af8265f0c8.pdf)
[5e7900aa998e17af8265f0c7.pdf](https://github.com/UW-COSMOS/Cosmos/files/5211545/5e7900aa998e17af8265f0c7.pdf)

looks like these docs are most indexes, lists not really fitting scientific paper structures.

**Dask Cluster Error**:
> Function:  xgboost_postprocess
> args:      ('tmp/images/5a15d754cf58f10f6558336a.pdf_2.pkl')
> kwargs:    {}
> Exception: ValueError('not enough values to unpack (expected 3, got 0)')

**Python Error**:

> (cosmos) [imcconnell2@cosmos0003 Cosmos]$ bash cli/ingest_documents_timing.sh 
> DEBUG :: 2020-08-14 00:55:48,331 :: Using selector: EpollSelector
> Traceback (most recent call last):       ] | 23% Completed | 30min 35.4s  1.4s
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/scripts/ingest_documents.py", line 43, in <module>
>     ingest_documents()
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/scripts/ingest_documents.py", line 39, in ingest_documents
>     aggregations=aggregation)
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/ingest.py", line 66, in ingest
>     aggregations=aggregations)
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/ingest.py", line 93, in _ingest_local
>     images = [i.result() for i in images]
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/ingest.py", line 93, in <listcomp>
>     images = [i.result() for i in images]
>   File "/home/imcconnell2/miniconda3/envs/cosmos/lib/python3.7/site-packages/distributed/client.py", line 223, in result
>     raise exc.with_traceback(tb)
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/process_page.py", line 71, in xgboost_postprocess
>     objects = postprocess(dp.postprocess_model, dp.classes, objects)
>   File "/ssd/iain/Cosmos/cosmos/ingestion/ingest/process/postprocess/xgboost_model/inference.py", line 9, in run_inference
>     p_bb, _, texts = zip(*page_objs)
> ValueError: not enough values to unpack (expected 3, got 0)

**Comment by ilmcconnell** [comment]
Seems like the issue is that each member of the list page_objs should consist of [tuple, list, string], but at least one member is missing one of those components.

Tried to replicate this by: 

1. using a simple print statement to get the last value for page_objs before the error. 
2. manually define page_objs with that output in local python session
3. attempt zip(*page_objs)
4. This worked, and threw no error. 

Maybe my initial hypothesis is wrong, using the print statement to get the value some how covered up a null value or I'm missing something else here.

Another attempt to replicate: 

1. I attempted to use remote debugging on cosmos0003 running the debugger from PyCharm on my laptop.
2. Error successfully replicated, but the debugger didn't return any values for page_objs

Currently exploring alternatives.

last value for page_objs before the error (from print statement):

> [
>    ((111.0,
>    134.0,
>    468.0,
>    157.0),
>    [
>       (2.2799901962280273,
>       'Section Header'),
>       (2.2257251739501953,
>       'Body Text'),
>       (1.9098150730133057,
>       'Page Header'),
>       (-0.19148534536361694,
>       'Page Footer'),
>       (-0.7117554545402527,
>       'Equation'),
>       (-0.8580109477043152,
>       'Reference text'),
>       (-1.9055906534194946,
>       'Figure Caption'),
>       (-2.299734592437744,
>       'Figure'),
>       (-2.5229454040527344,
>       'Other'),
>       (-3.8087916374206543,
>       'Table Caption'),
>       (-4.783747673034668,
>       'Table')
>    ],
>    'Hydrologic cycle and ecosystem'),
>    ((109.0,
>    189.0,
>    687.0,
>    793.0),
>    [
>       (8.901707649230957,
>       'Body Text'),
>       (0.27558329701423645,
>       'Page Header'),
>       (-0.7641305923461914,
>       'Page Footer'),
>       (-2.194887399673462,
>       'Section Header'),
>       (-2.9002270698547363,
>       'Reference text'),
>       (-2.9687256813049316,
>       'Equation'),
>       (-4.524193286895752,
>       'Figure'),
>       (-4.657354354858398,
>       'Figure Caption'),
>       (-6.540764331817627,
>       'Other'),
>       (-6.95805025100708,
>       'Table Caption'),
>       (-9.029019355773926,
>       'Table')
>    ],
>    'In arid- and semi-arid regions, the hydrologic regime undoubtedly exerts a strong inﬂuence on the fate of the ecosystem. This has been studied in this project with partic- ular emphasis on soil, soil erosion, and grasslands. In gen- eral, soils tend to reﬂect a longer term hydrologic history, while grasslands respond more quickly to the recent hydrology. In the central part of the Mongolian steppe, Miyazaki et al. (2004) already found prior to the RAISE project that precipitation and the changes in soil moisture content in the early growing season before July had the largest inﬂu- ence on the grass growth as measured by LAI. Similarly, Iwasaki (2005, 2006) have shown through analysis of the meteorological data at 97 IMH stations that there is a fairly strong correlation between vegetation activity and the monthly averages of the temperature and the precipita- tion. These results tend to indicate that the primary fac- tors that determine the rangelands biomass are indeed precipitation and temperature in early summer season but that there are probably other factors in some locations that need to be addressed. Kojima (2004)’s result that there is a negative correlation between the magnitude of the changes in biomass over a one month period and the'),
>    ((110.0,
>    1698.0,
>    1309.0,
>    1771.0),
>    [
>       (7.7887773513793945,
>       'Figure Caption'),
>       (1.077684998512268,
>       'Table Caption'),
>       (-0.2899866998195648,
>       'Body Text'),
>       (-1.6060024499893188,
>       'Page Header'),
>       (-1.8333526849746704,
>       'Page Footer'),
>       (-2.821833372116089,
>       'Section Header'),
>       (-5.228155612945557,
>       'Other'),
>       (-6.072132587432861,
>       'Table'),
>       (-7.288239479064941,
>       'Equation'),
>       (-7.507740020751953,
>       'Figure'),
>       (-7.987154483795166,
>       'Reference text')
>    ],
>    'Figure 6 Topographic map with a Landsat ETM+ true color image of the FOR site. Contour lines are shown at 30 m intervals, except for the upper side of the map as this is outside the ASTER image from which contour lines were created. The ﬂux station is indicated by a circle. Also shown at the upright corner is aerial photograph of the site.'),
>    ((109.0,
>    81.0,
>    1309.0,
>    107.0),
>    [
>       (2.2575924396514893,
>       'Page Header'),
>       (1.4581506252288818,
>       'Body Text'),
>       (0.2689821720123291,
>       'Equation'),
>       (-0.3489368259906769,
>       'Section Header'),
>       (-1.1644948720932007,
>       'Reference text'),
>       (-1.4279359579086304,
>       'Page Footer'),
>       (-1.4701637029647827,
>       'Other'),
>       (-2.8774330615997314,
>       'Figure'),
>       (-2.9259164333343506,
>       'Table Caption'),
>       (-3.449002981185913,
>       'Figure Caption'),
>       (-4.033204555511475,
>       'Table')
>    ],
>    'An overview of the rangelands atmosphere–hydrosphere–biosphere interaction 11'),
>    ((731.0,
>    134.0,
>    1309.0,
>    791.0),
>    [
>       (7.542834758758545,
>       'Body Text'),
>       (0.6768191456794739,
>       'Page Header'),
>       (-0.13711348176002502,
>       'Page Footer'),
>       (-2.116135835647583,
>       'Section Header'),
>       (-2.2084760665893555,
>       'Equation'),
>       (-2.490629196166992,
>       'Reference text'),
>       (-3.219329833984375,
>       'Figure Caption'),
>       (-3.641505479812622,
>       'Figure'),
>       (-6.005919933319092,
>       'Other'),
>       (-6.037735939025879,
>       'Table Caption'),
>       (-7.220633506774902,
>       'Table')
>    ],
>    'grazing pressure suggests that grazing activity is one of such factor. However, more studies will be needed to quantify such effects. Asano et al. (2006) made a detailed survey of soil proﬁles at ﬁve locations with annual precipitation ranges from about 130 to 200 mm. Their study shows that there are dif- ferences in soil chemistry and physics that clearly reﬂect the characteristics and amount of the precipitation and inﬁltration at each location. The presence of the different soil in turn means that the same environmental impacts or disturbances could result in quite different consequences in soils, even though the general soil class within the exper- imental area is classiﬁed as essentially the same Calcic Kas- tanozems and Calcic Hyposodic Kastanozems (Asano et al., 2006). Mariko et al. (this issue) studied experimentally the effect of water on the CO2 and CH4 ﬂuxes at the soil surface at KBU. Immediately after an artiﬁcial rainfall, CO2 emission from the soil to the atmosphere increased while the CH4 absorption by the soil decreased. It is suspected that the rainfall activated the microorganisms and resulted in changes in the ﬂuxes due to respiration. Thus the soil respi- ration depends not only the soil temperature but also the soil water content. This is another example of the profound relevance of water in controlling fate of the rangelands in various ways.'),
>    ((164.0,
>    866.0,
>    1261.0,
>    1675.0),
>    [
>       (6.967167854309082,
>       'Figure'),
>       (0.23296518623828888,
>       'Page Header'),
>       (-0.6925345659255981,
>       'Body Text'),
>       (-1.5247308015823364,
>       'Table'),
>       (-1.984200358390808,
>       'Page Footer'),
>       (-2.510521173477173,
>       'Equation'),
>       (-4.865751266479492,
>       'Figure Caption'),
>       (-5.048243999481201,
>       'Table Caption'),
>       (-5.809715747833252,
>       'Other'),
>       (-7.415019989013672,
>       'Section Header'),
>       (-7.802918434143066,
>       'Reference text')
>    ],
>    '')
> ]

**Comment by iross** [comment]
Fixed in https://github.com/UW-COSMOS/Cosmos/commit/3aaecfcc8729b3469744e80345a091fbb2fc8366.
