### ISSUE TITLE
Leverage in-text table mentions to expand context recall

### ISSUE THREAD

**Issue by iross** [UW-COSMOS/Cosmos#149]
(lots of development already done on this, just writing up a quick issue for tracking purposes)

# Executive summary
COSMOS extracts tables, figures, and their associated mentions. However, in-text mentions of these objects could expand contextual windows for these, or provide context for cases where caption association is missed.

@ilmcconnell could you write up a brief summary of the current status and the lingering items before it's ready for a final release?

**Comment by ilmcconnell** [comment]
@iross fixes to missing table reporting and COSMOS table detection statistics are in.

**Comment by ilmcconnell** [comment]
## Current status

1. Enable enrichment with the ingest --enrich option:
    1. After ingest process completes the enrichment process begins
    2. each pdf mentioned in the _tables aggregated parquet, has those rows and associated rows in the non aggregated parquet (body text) processed for context
    3. for each detected table's mention in the body text 20 words either side of that mention (40 word span) are collected
    4. all context spans are appended to the _tables aggregation parquet in a new column 'context_from_text'
2. enable qa evaluation with --qa option:
    1. enrichment process will also output:
        1. parquet with list of pdfs and each table mentioned in text not detected by COSMOS
        2. parquet of detection statistics per pdf (precision, recall, f1 score)
        3. parquet of macro-average detection statistics for all pdfs (precision, recall, f1 score)

**Comment by iross** [comment]
Still to do: Ian expand the ES retrieval ingest + search interface to include expanded context.

**Comment by iross** [comment]
API side updates in progress https://github.com/UW-COSMOS/Cosmos/tree/dev/api_update_jul2021

Now ingests the `context_from_text` column and appends it to the `full_content` field. Still to do: toggles to target specific fields.
