### ISSUE TITLE
 The parquet files not found in output directory

### ISSUE THREAD

**Issue by jackchenwen** [UW-COSMOS/Cosmos#160]
I run the command “docker-compose -f deployment/docker-compose-ingest.yml -p cosmos up”，and can not find parquet files in output directory .

[root@192-168-100-107 ~]# docker-compose -f /usr/Cosmos-master/deployment/docker-compose-ingest.yml -p cosmos up
[+] Running 4/0
 ⠿ Container cosmos-scheduler-1      Created                                                                                                                                                           0.0s
 ⠿ Container cosmos-worker-1         Created                                                                                                                                                           0.0s
 ⠿ Container cosmos-runner-1         Created                                                                                                                                                           0.0s
 ⠿ Container cosmos-detect_worker-1  Created                                                                                                                                                           0.0s
Attaching to cosmos-detect_worker-1, cosmos-runner-1, cosmos-scheduler-1, cosmos-worker-1
cosmos-scheduler-1      | distributed.scheduler - INFO - -----------------------------------------------
cosmos-scheduler-1      | distributed.http.proxy - INFO - To route to workers diagnostics web server please install jupyter-server-proxy: python -m pip install jupyter-server-proxy
cosmos-scheduler-1      | distributed.scheduler - INFO - -----------------------------------------------
cosmos-scheduler-1      | distributed.scheduler - INFO - Clear task state
cosmos-scheduler-1      | distributed.scheduler - INFO -   Scheduler at:     tcp://172.18.0.3:8786
cosmos-scheduler-1      | distributed.scheduler - INFO -   dashboard at:                     :8787
cosmos-worker-1         | distributed.preloading - INFO - Import preload module: ingest.preload_plugins.process_setup
cosmos-worker-1         | distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.1.92:40734'
cosmos-runner-1         | DEBUG :: 2022-03-09 05:56:10,913 :: Using selector: EpollSelector
cosmos-detect_worker-1  | distributed.preloading - INFO - Import preload module: ingest.preload_plugins.detect_setup
cosmos-detect_worker-1  | distributed.nanny - INFO -         Start Nanny at: 'tcp://10.0.1.91:40329'
cosmos-runner-1         | Usage: ingest_documents.py [OPTIONS]
cosmos-runner-1         | Try 'ingest_documents.py --help' for help.
cosmos-runner-1         | 
cosmos-runner-1         | Error: no such option: --use-table-context-enrichment
cosmos-worker-1         | distributed.preloading - INFO - Import preload module: ingest.preload_plugins.process_setup
cosmos-worker-1         | /ingestion/ingest/preload_plugins/process_setup.py:18: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
cosmos-worker-1         |   self.classes = yaml.load(stream)["CLASSES"]
cosmos-worker-1         | distributed.preloading - INFO - Run preload setup click command: ingest.preload_plugins.process_setup
cosmos-worker-1         | distributed.worker - INFO -       Start worker at:      tcp://10.0.1.92:37697
cosmos-worker-1         | distributed.worker - INFO -          Listening to:      tcp://10.0.1.92:37697
cosmos-worker-1         | distributed.worker - INFO -          dashboard at:            10.0.1.92:34960
cosmos-worker-1         | distributed.worker - INFO - Waiting to connect to:       tcp://scheduler:8786
cosmos-worker-1         | distributed.worker - INFO - -------------------------------------------------
cosmos-worker-1         | distributed.worker - INFO -               Threads:                          1
cosmos-worker-1         | distributed.worker - INFO -       Local Directory: /ingestion/dask-worker-space/dask-worker-space/worker-n9abar3z
cosmos-worker-1         | distributed.worker - INFO - Starting Worker plugin <ingest.preload_plugins.process_setup.ProcessPlugi-25d4fdc0-d8d3-4ba0-a2ef-e6418f12ec0a
cosmos-worker-1         | distributed.worker - INFO - -------------------------------------------------
cosmos-scheduler-1      | distributed.scheduler - INFO - Register worker <Worker 'tcp://10.0.1.92:37697', name: tcp://10.0.1.92:37697, memory: 0, processing: 0>
cosmos-scheduler-1      | distributed.scheduler - INFO - Starting worker compute stream, tcp://10.0.1.92:37697
cosmos-worker-1         | distributed.worker - INFO -         Registered to:       tcp://scheduler:8786
cosmos-worker-1         | distributed.worker - INFO - -------------------------------------------------
cosmos-scheduler-1      | distributed.core - INFO - Starting established connection
cosmos-worker-1         | distributed.core - INFO - Starting established connection
cosmos-runner-1 exited with code 2
cosmos-detect_worker-1  | distributed.preloading - INFO - Import preload module: ingest.preload_plugins.detect_setup
cosmos-detect_worker-1  | distributed.preloading - INFO - Run preload setup click command: ingest.preload_plugins.detect_setup
cosmos-detect_worker-1  | distributed.worker - INFO -       Start worker at:      tcp://10.0.1.91:33755
cosmos-detect_worker-1  | distributed.worker - INFO -          Listening to:      tcp://10.0.1.91:33755
cosmos-detect_worker-1  | distributed.worker - INFO -          dashboard at:            10.0.1.91:42501
cosmos-detect_worker-1  | distributed.worker - INFO - Waiting to connect to:       tcp://scheduler:8786
cosmos-detect_worker-1  | distributed.worker - INFO - -------------------------------------------------
cosmos-detect_worker-1  | distributed.worker - INFO -               Threads:                          1
cosmos-detect_worker-1  | distributed.worker - INFO -       Local Directory: /ingestion/dask-worker-space/dask-worker-space/worker-w_nho1re
cosmos-detect_worker-1  | distributed.worker - INFO - Starting Worker plugin <ingest.preload_plugins.detect_setup.DetectPlugin -9e803943-8651-4cfc-81b5-156148c766f8
cosmos-detect_worker-1  | distributed.worker - INFO - -------------------------------------------------
cosmos-scheduler-1      | distributed.scheduler - INFO - Register worker <Worker 'tcp://10.0.1.91:33755', name: tcp://10.0.1.91:33755, memory: 0, processing: 0>
cosmos-scheduler-1      | distributed.scheduler - INFO - Starting worker compute stream, tcp://10.0.1.91:33755
cosmos-scheduler-1      | distributed.core - INFO - Starting established connection
cosmos-detect_worker-1  | distributed.worker - INFO -         Registered to:       tcp://scheduler:8786
cosmos-detect_worker-1  | distributed.worker - INFO - -------------------------------------------------
cosmos-detect_worker-1  | distributed.core - INFO - Starting established connection

this is .env

BASE_IMAGE=uwcosmos/cosmos-base-cpu:latest
DETECT_IMAGE=uwcosmos/cosmos-ingestion-cpu:latest
WORKER_IMAGE=uwcosmos/cosmos-ingestion-cpu:latest
RETRIEVAL_IMAGE=uwcosmos/cosmos-retrieval-cpu:latest
EXTRACTION_IMAGE=ankurgos/cosmos-extraction-cpu:latest
VISUALIZER_IMAGE=uwcosmos/visualizer_kb-cpu:latest
LINKING_IMAGE=uwcosmos/cosmos-linking-cpu:latest
UPLOAD_IMAGE=uwcosmos/cosmos-api-cpu:latest
API_IMAGE=uwcosmos/cosmos-api-cpu:latest

SCHEDULER_ADDRESS=scheduler:8786
ELASTIC_ADDRESS=es01:9200
NUM_PROCESSES=1

WORKER_PROCS=1
DETECT_PROCS=1

# Default to GPU
#DEVICE=cuda
#RERANKING_DEVICE=cuda

# Uncomment to use CPUs
DEVICE=cpu
RERANKING_DEVICE=cpu

# Env vars for training
TRAINING_DIR=/usr/cosmos/training_data
VALIDATION_DIR=/usr/cosmos/validation_data
CONFIG_DIR=${PWD}/deployment/configs
WEIGHTS_DIR=/usr/cosmos/training_output

# Env vars for primary pipeline
INPUT_DIR=/usr/cosmos/pdfs
TMP_DIR=/usr/cosmos/tmp
OUTPUT_DIR=/usr/cosmos/output
ELASTIC_DATA_PATH=/usr/cosmos/elasticsearch

**Comment by RichardScottOZ** [comment]
So on this one

Writes things to temp directory - at what stage do you expect to see output - e.g. working/not working - per file/worker job or all at the end?

Haven't had tiem to digest all the code as yet, sorry.

**Comment by RichardScottOZ** [comment]
Testing on a not that impressive machine but does have a 24GB gpu, I just left it at the default PROC/WOKER numbers

```bash
 PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
30737 root      20   0 6017288 3.656g 152480 S 102.7 11.8 113:14.47 python3.8
30041 root      20   0 1154276 355576  39648 S   9.0  1.1  16:31.49 dask-scheduler
30226 root      20   0 2855796 167980  58136 R   3.7  0.5   4:37.07 dask-worker
30561 root      20   0 3464460 628032 172920 S   2.3  1.9  12:40.62 python3.8
30550 root      20   0 3329896 490296 172880 S   2.0  1.5  12:10.79 python3.8
30553 root      20   0 3460444 627172 173124 S   2.0  1.9  13:31.27 python3.8
30557 root      20   0 3461712 630872 172760 S   2.0  1.9  12:21.35 python3.8
30565 root      20   0 3603740 760952 172064 S   2.0  2.3  12:13.14 python3.8
30574 root      20   0 3468772 631712 172168 S   2.0  1.9  12:19.38 python3.8
30569 root      20   0 3461620 623408 172252 S   1.7  1.9  12:01.31 python3.8
30576 root      20   0 3426160 601428 172904 S   1.7  1.8  16:51.17 python3.8
30383 root      20   0 2213932 274448 139332 S   1.0  0.8   1:27.01 dask-worker
29813 ubuntu    20   0  554556  70940   9528 S   0.7  0.2   0:22.43 docker-compose
26729 root      20   0 1499400  50144  28256 S   0.3  0.2   0:02.62 containerd
28547 root      20   0 1802856 132844  55960 S   0.3  0.4   3:16.77 dockerd
    1 root      20   0  225536   9440   6788 S   0.0  0.0   0:05.21 systemd
```
