### ISSUE TITLE
Worker question

### ISSUE THREAD

**Issue by RichardScottOZ** [UW-COSMOS/Cosmos#166]
Do you have an ballpark rules of thumb on setup for:

Depending on your machine, you can scale the process by setting DETECT_PROCS and WORKER_PROCS to the desired number of processes.

e.g. gpu size/RAM/cpu count etc?

Thanks!

**Comment by RichardScottOZ** [comment]
So rough guide to 'how long will this take with this many documents of the usual size'?

**Comment by iross** [comment]
Quick updates in https://github.com/UW-COSMOS/Cosmos/commit/733599ffbfa904b80aa795890edc928d6e7798e8 and https://github.com/UW-COSMOS/Cosmos/commit/accbd0690505b9206aca517df2f6e33422a8c909.

GPUs are untested below 8GB of memory. I think it could potentially work with 4GB, but I doubt it'd work below that. Processing takes just a minute or two for a ~10 page document (depending on what options you're running).
