### ISSUE TITLE
XGBoost Error

### ISSUE THREAD

**Issue by Deven-Biehler** [UW-COSMOS/Cosmos#183]
Hi, I'm getting the error 
"xgboost.core.XGBoostError: [19:37:37] ../src/learner.cc:1017: Check failed: fi->Read(&mparam_, sizeof(mparam_)) == sizeof(mparam_) (132 vs. 136) : BoostLearner: wrong model format" when trying to run "docker-compose -f deployment/docker-compose-ingest-newdc.yml -p cosmos up".

Here is my .env file:

BASE_IMAGE=uwcosmos/cosmos-base
DETECT_IMAGE=uwcosmos/cosmos-ingestion
WORKER_IMAGE=uwcosmos/cosmos-ingestion
RETRIEVAL_IMAGE=uwcosmos/cosmos-retrieval
EXTRACTION_IMAGE=ankurgos/cosmos-extraction:latest
VISUALIZER_IMAGE=uwcosmos/visualizer_kb:latest
UPLOAD_IMAGE=iaross/cosmos-api:latest
API_IMAGE=iaross/cosmos-api:latest
LINKING_IMAGE=uwcosmos/cosmos-linking

DETECT_PROCS=1
WORKER_PROCS=8

DEVICE=cuda
RERANKING_DEVICE=cuda

SCHEDULER_ADDRESS=scheduler:8786
ELASTIC_ADDRESS=es01:9200
INPUT_DIR=../test/input
TMP_DIR=../test/mytmp
OUTPUT_DIR=../test/output
ELASTIC_DATA_PATH=../test/example_elastic_out

here is my output of the error when running docker-compose -f deployment/docker-compose-ingest-newdc.yml -p cosmos up:

![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/b4a1f956-01d6-4cf1-8727-9fab976aed42)

The entire output is below:
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/6df99c11-ba19-49b3-bf8f-87e5a0b277c0)
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/0cd2e8a9-acb7-4fdb-acb7-3b0d7aa85942)
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/bc3acfd4-fe31-4162-b3bc-4c206ff1bebf)
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/9f9f611a-b2eb-4ce9-90dd-c1d2bfbc5898)
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/4dd47dc3-5f93-4a5b-ab76-1b397b9b2f67)
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/e8c418e4-a7b3-4b94-bdc2-1de9aee2e057)
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/90528271-b737-41e1-b523-f698ef15dee7)

**Comment by iross** [comment]
Hello--
What's the output of

```
docker inspect uwcosmos/cosmos-ingestion | grep -A 2 RepoDigests
```
?

**Comment by Deven-Biehler** [comment]
> 

"RepoDigests": [],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",

**Comment by Deven-Biehler** [comment]
I fixed this by simply removing the images that I had running and rerunning the command.
