### ISSUE TITLE
Timeout after 10 seconds?

### ISSUE THREAD

**Issue by Deven-Biehler** [UW-COSMOS/Cosmos#184]
Hi, Im getting an error during the Entity Linking when running the command: "docker-compose -f deployment/docker-compose-link.yml -p cosmos up".

The error is here:
"OSError: Timed out during handshake while connecting to tcp://scheduler:8786 after 10 s"

Full output here:
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/6ee711df-ec76-4e5b-b62f-58ad1f8c5ef6)
![image](https://github.com/UW-COSMOS/Cosmos/assets/124630485/9b8c8a88-c76c-47c6-9a6a-b30f781b42f8)

I have tried to extend the timeout time in the config/config.yaml file with the code:
“distributed:
  Scheduler:	
    rpc:
      timeout: 60”
with no luck.

Here is my .env file:

BASE_IMAGE=uwcosmos/cosmos-base
DETECT_IMAGE=uwcosmos/cosmos-ingestion
WORKER_IMAGE=uwcosmos/cosmos-ingestion
RETRIEVAL_IMAGE=uwcosmos/cosmos-retrieval
EXTRACTION_IMAGE=ankurgos/cosmos-extraction:latest
VISUALIZER_IMAGE=uwcosmos/visualizer_kb:latest
UPLOAD_IMAGE=iaross/cosmos-api:latest
API_IMAGE=iaross/cosmos-api:latest
LINKING_IMAGE=uwcosmos/cosmos-linking

DETECT_PROCS=1
WORKER_PROCS=8

DEVICE=cuda
RERANKING_DEVICE=cuda

SCHEDULER_ADDRESS=scheduler:8786
ELASTIC_ADDRESS=es01:9200
INPUT_DIR=../test/input
TMP_DIR=../test/mytmp
OUTPUT_DIR=../test/output
ELASTIC_DATA_PATH=../test/example_elastic_out

**Comment by iross** [comment]
I've pushed a new version of the image which should resolve this. I also updated the docker-compose file, which was also using the deprecated `nprocs` argument.
