### ISSUE TITLE
Expecting `.png` but receiving `.jpg`

### ISSUE THREAD

**Issue by brandomr** [UW-COSMOS/Cosmos#201]
With [this paper](https://github.com/DARPA-ASKEM/knowledge-middleware/blob/main/tests/scenarios/basic/paper.pdf) we can obtain the zip results from http://xdd.wisc.edu/cosmos_service/process/5eaa01f3-1eae-4a31-b153-9139b13b9575/result. In the [equations response from Cosmos](https://xdd.wisc.edu/cosmos_service/process/5eaa01f3-1eae-4a31-b153-9139b13b9575/result/extractions/equations) there is reference to 

```
{"pdf_name":"paper.pdf","page_num":"3","bounding_box":[727,1554,991,1719],"detect_score":-2.6257579327,"content":null,"postprocess_score":0.6855009198,"img_pth":"http://xdd.wisc.edu/cosmos_service/process/5eaa01f3-1eae-4a31-b153-9139b13b9575/result/images/48db207c-f31b-4087-b5d7-3f5ce4eb24ec.png"}
```

but the zipfile only contains `.jpg`. 

Is this a recent change? We can look for `.jpg` but right now we just look exactly for what is listed by the endpoints so are expecting to see `48db207c-f31b-4087-b5d7-3f5ce4eb24ec.png`

**Comment by iross** [comment]
We haven't deployed a new version in a few weeks, so I'm pretty baffled why
this is popping up now. Maybe there was a cached result you were grabbing
that expired and then kicked off a new processing that had different
modality. When you submit a run, you can specify `compress_images` -- False
will return the full PNG, True compresses them to JPG. There's also the
`use_cache` parameter which can be used to force a new processing each time:

https://xdd.wisc.edu/cosmos_service/docs#/default/process_document_cosmos_service_process__post

**Comment by brandomr** [comment]
Got it, will try to ask for uncompressed images. I'll close this now and reopen if we can't get that working.
