### ISSUE TITLE
Exiting with code 137

### ISSUE THREAD

**Issue by Rzfeng** [UW-COSMOS/Cosmos#39]
When running the docker image in the build model phase, it may exit with code 137.

If this happens you should increase your memory in your Docker settings/preferences. By default, it's 2GB, increase it to at least 4GB and if the issue persists, keep increasing it.

(visual of how to change memory in preferences below)
https://www.petefreitag.com/item/848.cfm

**Comment by cambro** [comment]
More information on error codes and suggestions in README.md here:
https://github.com/UW-COSMOS/cosmos-demo

**Comment by ankur-gos** [comment]
Stale, closing.
