### ISSUE TITLE
Obfuscate page_ids

### ISSUE THREAD

**Issue by iross** [UW-COSMOS/Cosmos#95]
Pages should have UUIDs (or similar) instead of a integer id. Right now, a user could trivially step through a bunch of pages and recreate a full PDF.

**Comment by cambro** [comment]
This should apply to all objects in COSMOS API.

**Comment by ankur-gos** [comment]
Is this issue stale? @iross

**Comment by iross** [comment]
Very stale. It hasn't been integer ids in a long time.
