### ISSUE TITLE
Anserini/ES returns figure captions with no figures in figure search

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/Cosmos#98]
See example from search for "coronavirus lungs" caption is returned with no associated figure. is this expected behavior? Does it mean that COSMOS was unable to associate the caption with a figure element?
<img width="841" alt="capt" src="https://user-images.githubusercontent.com/6107153/78902912-0b0b3180-7a40-11ea-9cd9-dcab940a115c.png">

**Comment by iross** [comment]
I think this is a side effect of our visualizer/API development being a bit of out-of-sync. It looks like the visualizer isn't showing the parent (header) objects from the API response, just the children. I see Daven made the changes on the visualizer side (https://github.com/UW-COSMOS/cosmos-visualizer/commit/f63067ba0f1aa2004f0a2fb2ae05cbcebfcfd860) but I'm not sure if they're live -- @davenquinn?

**Comment by davenquinn** [comment]
I have not made those changes live yet, although they are fixed in the codebase. Will do shortly

**Comment by ankur-gos** [comment]
Closing this as we are deprecating the Anserini retrieval.
