### ISSUE TITLE
API route to summarize COSMOS vertical corpus 

### ISSUE THREAD

**Issue by cambro** [UW-COSMOS/Cosmos#99]
An API route containing details about the underlying corpus in a vertical set (e.g., COVID19) should be made available. 
This route should include basic data size statistics as well as a breakdown of number of documents by publisher and journal title (when available). It would be wise to pre-compute this and store it in a lookup table that gets updated when new documents are added.

**Comment by davenquinn** [comment]
If possible, this should also contain a brief statement of the corpus targeting (e.g. 'novel coronavirus') and updated date

**Comment by ankur-gos** [comment]
I believe this enhancement has been merged in. @iross confirm?
